---
# tasks file for ubuntu_httpd

- name: install httpd
  ansible.builtin.apt:
    name: apache2
    state: present

- name: start and enable httpd
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: copy index.html
  ansible.builtin.copy:
    src: index.html 
    dest: /var/www/html/index.html

- name: reconfigure port number
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
  notify:
    - restart apache2

...
