---
# tasks file for httpd
#

- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Start and enable httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

    #- name: copy the index file to the apache server
     # ansible.builtin.copy:
      #  src: index.html
       # dest: /var/www/html/index.html
