---
# tasks file for httpd
#

- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: installed

- name: Start and enable httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: copy the index file to the apache server
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

- name: httpd port configuration
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: 
    - restart httpd
...
